FROM ollama/ollama

EXPOSE 11434

#RUN ollama pull llama3.1
#RUN ollama pull gemma3:1b

ENV OLLAMA_HOST=0.0.0.0:11434

# both lines deprecated it runs by default now
#ENTRYPOINT ["/bin/ollama"]
#CMD ["serve"]

